script: "bundle exec rake"
before_install: gem update --system
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - ruby-head
  - ree
  - jruby
  - rbx-18mode
gemfile:
  - gemfiles/Gemfile-rails.3.0.x
  - gemfiles/Gemfile-rails.3.1.x
  - Gemfile
